language: node_js
sudo: false

node_js:
  - "10.15.3"

before_install:
  - npm install -g npm@5

install:
  - npm install

env:
  global:
    - export NODE_ENV=test

after_success:
  - npm run coverage:all
