export const GENERATE_NUMBERS = 'GENERATE_NUMBERS';
export const GET_ALL_NUMBERS = 'GET_ALL_NUMBERS';
export const CLEAR_ALL_NUMBERS = 'CLEAR_ALL_NUMBERS';
export const SORT_NUMBERS = 'SORT_NUMBERS';
